### ISSUE TITLE
Re-implement weather model page in GUI

### ISSUE THREAD

**Issue by masonwillman** [firelab/windninja#637]
Work should be completed in a new branch called GUI-Redesign-weather-model. Tasks that need completed include:

- [x] Simplifying the weather model page in the GUI (using QT Designer)
- [x] Enabling the reading of weather models through the API (reference the old GUI)
- [x] The fetching of weather models through the API
- [x] The reading and selection of specific timesteps through the API
- [x] Weather model works with all outputs

Add to the list as more features need implemented.

**Comment by masonwillman** [comment]
As of commit https://github.com/firelab/windninja/commit/006911fa236526f802bac31ff5e6fe2fe74db828, the GUI resembles the old style with the latest code from the GUI-Redesign branch. Another branch will need to be made to continue this work as the old branch was merged due to worsening divergence between it and the GUI-Redesign branch in commit f264eacb3e7b57b7611c328bd45ccca14a24cb9d.

**Comment by masonwillman** [comment]
Attempted to implement user specified time steps in commit [d6286cf](https://github.com/firelab/windninja/commit/d6286cfa7cbc43b8a1fc2205e0ffad65bad17fb7). Had to comment out the code that set the timeList in the API as it was causing weird behavior. 

Specifically, in `nomads_wx_init.cpp` the function `set_surface_grids` calls the `getTimeList` function for the weather model file selected. Then, there is an if statement `if(timeList[i] == ninja.inputTime)` where the code iterates through the timeList and finds which time matches the inputTime for that ninja. However, when I add my code to specify the times in the API,  the timeList value used in the comparison is incorrect. The ninja.inputTime is correct, but the timeList[i] value is off by a couple hours. I've been comparing this to the old GUI but have been unable to find the reason for the discrepancy. [Link to the function.](https://github.com/firelab/windninja/blob/master/src/ninja/nomads_wx_init.cpp#L514-L554).

**Comment by latwood** [comment]
@masonwillman this sounds about right, I would have to double check the code to make sure, but I'm currently effectively on break.

When we did the release of the Archived HRRR, I did have to do a lot of work to get the time zone stuff correct, I definitely made changes to what you had committed to get the time zones correct. So whatever is currently implemented in the cli and the old gui should be correct.

Whether that truly matches up with the behavior of the other weather models or point init may be a separate question, for now I would recommend just matching the behavior for Archived HRRR. I would recommend getting caught up on the current behavior by doing some testing using a missoula dem and a seattle downloaded dem, swapping back and forth between those two time zones. If I remember correctly, it should always try to auto-populate the starting times using 1 hr back from whatever the current hour is, in the local time specified by the time zone (which is usually the time zone of the dem, but not always).

**Comment by latwood** [comment]
No problem. And the important thing is the behavior, if it turns out that you can replicate the local time to UTC, and UTC to local time, using some new QT method that works and is consistent across the code, then that would be better.

And yes, I'm pretty sure by local time, it is time zone local, not machine local. But it would probably be tough to be able to tell which it is without straight up testing input vs output.

Watch out for, if it is boost date time stuff, the type of constructor. Whether the input time is local time with a time zone, or utc time, depends on the constructor arguments, I believe I commented that in the code but it is possible that I took such comments out after cleanup.

**Comment by masonwillman** [comment]
I'll reference the code as needed. My hope is to implement it via QT's date time methods. I just pushed my commit that has archive HRRR working. The next steps are the refinement of that (the local time conversion), progress bar implementation for all models, and general class clean up.

**Comment by latwood** [comment]
So it sounds like `QDateTime` in `qt6` still doesn't handle timezone specific local time rather than machine local time? I remember when I tried to edit a `QDateTime` in `qt4` with the appropriate timezone, I kind of just pretended it was a UTC time the whole time, and added in a time offset calculated using the timezone. But calculating the time offset using the timezone was a real pain, even with boost, it was way easier to just use boost date time constructors as an intermediary.

Is there no way to construct the `QDateTimeEdits` using a timezone, that overrides the machine local time, with a timezone local time? Or a way to change the timezone after construction without messing up the time? Though timezone overriding in this way would likely require some kind of extra setting, to specify which type of time to output, at each use for it to work.

Whether to use a "QDateTime" widget, or to just keep using boost library methods in a given time conversion function as needed, probably depends on how reliably it would work, and the frequency of the time conversions. Personally, I think long term it might be nice to setup some kind of time library utility within the ninja code, to try to keep time conversion methods more universal, kind of like gdal_util.cpp. That would also require corresponding C-API calls though. For now, it's probably just easier to make the time conversion functions as needed, trying to keep the methods universal.
